Appt.create!([
  {poll_id: 115, scheduled_slot: "2017-07-16 21:30:00", chosen: nil},
  {poll_id: 115, scheduled_slot: "2017-07-19 00:00:00", chosen: nil},
  {poll_id: 115, scheduled_slot: "2017-07-21 09:00:00", chosen: nil}
])
Poll.create!([
  {admin_id: 6, title: "Birthday", status: "Open", invitee: "Tash David", location: "restaurant", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 17, title: "c", status: "great!", invitee: nil, location: "c", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 17, title: "c", status: "c", invitee: nil, location: "c", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 17, title: "d", status: "d", invitee: nil, location: "d", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 17, title: "c", status: "c", invitee: nil, location: "c", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 18, title: "c", status: "c", invitee: nil, location: "c", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 18, title: "c", status: "c", invitee: nil, location: "c", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 18, title: "c", status: "c", invitee: nil, location: "c", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 18, title: "d", status: "d", invitee: nil, location: "d", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 18, title: "d", status: "d", invitee: nil, location: "d", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 18, title: "e", status: "e", invitee: nil, location: "e", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 18, title: "e", status: "e", invitee: nil, location: "e", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 18, title: "e", status: "e", invitee: nil, location: "e", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 19, title: "f", status: "f", invitee: nil, location: "f", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 20, title: "z", status: "z", invitee: nil, location: "z", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 20, title: "b", status: "b", invitee: nil, location: "b", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 20, title: "h", status: "h", invitee: nil, location: "h", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 20, title: "h", status: "h", invitee: nil, location: "h", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 20, title: "r", status: "r", invitee: nil, location: "r", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 21, title: "y", status: "y", invitee: nil, location: "y", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 22, title: "", status: "", invitee: nil, location: "", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 22, title: "", status: "", invitee: nil, location: "", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 22, title: "", status: "", invitee: nil, location: "", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 22, title: "", status: "", invitee: nil, location: "", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 22, title: "", status: "", invitee: nil, location: "", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 22, title: "", status: "", invitee: nil, location: "", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 22, title: "", status: "", invitee: nil, location: "", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 22, title: "", status: "", invitee: nil, location: "", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 22, title: "", status: "", invitee: nil, location: "", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 22, title: "", status: "", invitee: nil, location: "", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 22, title: nil, status: "", invitee: nil, location: nil, address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 22, title: "Birthday", status: "Open", invitee: nil, location: "Mimi's", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 23, title: "Baby Shower", status: "Yes", invitee: nil, location: "Tash's", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 24, title: "asdf", status: "Yes", invitee: nil, location: "assdf", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 24, title: "asdf", status: "Yes", invitee: nil, location: "assdf", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 25, title: "Birthday", status: "a", invitee: nil, location: "a", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 26, title: "asdf", status: "a", invitee: nil, location: "asdf", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 26, title: "asdf", status: "a", invitee: nil, location: "asdf", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 26, title: "asdf", status: "a", invitee: nil, location: "asdf", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 27, title: "Birthday", status: "a", invitee: nil, location: "a", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 27, title: "Birthday", status: "a", invitee: nil, location: "a", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 27, title: "Birthday", status: "a", invitee: nil, location: "a", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 27, title: "Birthday", status: "a", invitee: nil, location: "a", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 27, title: "Birthday", status: "a", invitee: nil, location: "a", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: "Baby Shower", status: "In progress", invitee: nil, location: nil, address: "100 S Street", city: "Chicago", state: "IN", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 49, title: "Running Group", status: "In progress", invitee: nil, location: nil, address: "100 N Adams Street", city: "Anywhere", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 49, title: "BBQ", status: "In progress", invitee: nil, location: nil, address: "700 S Main Street", city: "Chicago", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: "g", status: "g", invitee: nil, location: "g", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: "y", status: "y", invitee: nil, location: "y", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 29, title: "y", status: "n", invitee: nil, location: "y", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 33, title: "r", status: "r", invitee: nil, location: "r", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: "h", status: "f", invitee: nil, location: "h", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: "y", status: "y", invitee: nil, location: "y", address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: "a", status: "a", invitee: nil, location: nil, address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: "e", status: "In progress", invitee: nil, location: nil, address: "e", city: "e", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: "a", status: "In progress", invitee: nil, location: nil, address: "a", city: "a", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: nil, status: "In progress", invitee: nil, location: nil, address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: nil, status: "In progress", invitee: nil, location: nil, address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: nil, status: "In progress", invitee: nil, location: nil, address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: nil, status: "In progress", invitee: nil, location: nil, address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: nil, status: "In progress", invitee: nil, location: nil, address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: nil, status: "In progress", invitee: nil, location: nil, address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: nil, status: "In progress", invitee: nil, location: nil, address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: nil, status: "In progress", invitee: nil, location: nil, address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: nil, status: "In progress", invitee: nil, location: nil, address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: nil, status: "In progress", invitee: nil, location: nil, address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: nil, status: "In progress", invitee: nil, location: nil, address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: nil, status: "In progress", invitee: nil, location: nil, address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: nil, status: "In progress", invitee: nil, location: nil, address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: nil, status: "In progress", invitee: nil, location: nil, address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: nil, status: "In progress", invitee: nil, location: nil, address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: nil, status: "In progress", invitee: nil, location: nil, address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: "Birthday", status: "In progress", invitee: nil, location: nil, address: "22 Main Street", city: "City", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: nil, status: "In progress", invitee: nil, location: nil, address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: nil, status: "In progress", invitee: nil, location: nil, address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: nil, status: "In progress", invitee: nil, location: nil, address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: nil, status: "In progress", invitee: nil, location: nil, address: nil, city: nil, state: nil, invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: "HHHH", status: "Okay", invitee: nil, location: "a", address: "222 ", city: "Carroll", state: "AK", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: "Cat", status: "In progress", invitee: nil, location: nil, address: "a", city: "a", state: "AK", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: "Shower", status: "In progress", invitee: nil, location: nil, address: "400", city: "Anytown", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: "Shower", status: "In progress", invitee: nil, location: nil, address: "400", city: "Anytown", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 48, title: "BBQ", status: "In progress", invitee: nil, location: nil, address: "300", city: "Anytown", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: "Pool Party", status: "In progress", invitee: nil, location: "g", address: "Pool", city: "Chicago", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 6, title: "Capstone Presentation", status: "In progress", invitee: nil, location: "215 W. Ohio Street, Chicago, IL", address: "215 W Ohio Street", city: "Chicago", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: "Thanksgiving", status: "In progress", invitee: nil, location: nil, address: "200 S Clark St.", city: "Chicago", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: "Party", status: "In progress", invitee: nil, location: nil, address: "300 S Clark", city: "Chicago", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: "Baby Shower", status: "In progress", invitee: nil, location: nil, address: "100 S Street", city: "Chicago", state: "IN", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 49, title: "Bachelor Party", status: "In progress", invitee: nil, location: nil, address: "700 S Clark Street", city: "Chicago", state: "IN", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 49, title: "Picnic", status: "In progress", invitee: nil, location: nil, address: "Mills Park", city: "Oak Park ", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 30, title: "Birthday", status: "In progress", invitee: nil, location: nil, address: "200 S Clark St", city: "Chicago", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 30, title: "Birthday", status: "In progress", invitee: nil, location: nil, address: "200 S Clark St", city: "Chicago", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 30, title: "Pool Pary", status: "In progress", invitee: nil, location: nil, address: "200 S Clark St", city: "Chicago", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 30, title: "Pool Pary", status: "In progress", invitee: nil, location: nil, address: "200 S Clark St", city: "Chicago", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 30, title: "BBQ", status: "In progress", invitee: nil, location: nil, address: "20 S Clark St", city: "Chicago", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: "Coffee Meeting", status: "In progress", invitee: nil, location: nil, address: "300 S Dearborn ", city: "Chicago", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 50, title: "Joy's Meeting", status: "In progress", invitee: nil, location: nil, address: "400 N. Lake Street", city: "Chicago", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 50, title: "Joy's Meeting", status: "In progress", invitee: nil, location: nil, address: "400 N. Lake Street", city: "Chicago", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 50, title: "Ice Cream Social", status: "In progress", invitee: nil, location: nil, address: "100 N Pleasant Street", city: "Chicago", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 50, title: "Beach Party", status: "In progress", invitee: nil, location: nil, address: "100 N Lakeshore", city: "Chicago", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 50, title: "Beach Party", status: "In progress", invitee: nil, location: nil, address: "100 N Lakeshore", city: "Chicago", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 50, title: "Beach Party", status: "In progress", invitee: nil, location: nil, address: "100 N Lakeshore", city: "Chicago", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 50, title: "Hiking party", status: "In progress", invitee: nil, location: nil, address: "100 Forest Lane", city: "Chicago", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 50, title: "Running Club", status: "In progress", invitee: nil, location: nil, address: "500 W Lake Street", city: "Chicago", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: "Zoo", status: "In progress", invitee: nil, location: nil, address: "200 N Lincoln Ave", city: "Chicago", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: "Garden", status: "In progress", invitee: nil, location: nil, address: "400 N. Lake Street", city: "Oak Park", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: "Lake", status: "In progress", invitee: nil, location: nil, address: "200 N Lincoln Ave", city: "Chicago", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: "Party", status: "In progress", invitee: nil, location: nil, address: "200 N Lincoln Ave", city: "Chicago", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: "Party", status: "In progress", invitee: nil, location: nil, address: "500 W Lake Street", city: "Chicago", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil},
  {admin_id: 1, title: "Party all the time", status: "In progress", invitee: nil, location: nil, address: "500 W Lake Street", city: "Chicago", state: "IL", invitee2: nil, invitee3: nil, invitee4: nil}
])
Response.create!([
  {user_id: 4, appt_id: 1, answer: "something"},
  {user_id: 5, appt_id: 2, answer: "asdfgh"}
])
User.create!([
  {email: "emily@gmail.com", name: "Emily Flanagan", password_digest: "$2a$10$YCPRF89YWHNNJwqP80lXxu1BUYRHgdbMOBMI1nvKRWxIwcXgjHVbe"},
  {email: "tash@gmail.com", name: "Tash David", password_digest: "$2a$10$.Wbut1j22fP6B1hOv8fzhui2ga68OYDNFUNh6ip3sMe4WJPa2Zj5."},
  {email: "admin@gmail.com", name: "Admin", password_digest: "$2a$10$nxRsY6dRJ8PinHJ0NZ4hbutMScaG/A7b2vKhfmS/rU4PF0C9nVcO2"},
  {email: "emily@gmail.com", name: "Emily Flanagan", password_digest: "$2a$10$Yd72/aYu3BR7u7Q8M4WgAOsqBqCs4o6A57E5NlG/69wuEc74AIaVi"},
  {email: "tash@gmail.com", name: "Tash David", password_digest: "$2a$10$7EH3tL7.TIIE7Jvn.g0I3.wOlCJ2SN25ReNpT.FlOqoqfg4s7S9Nm"},
  {email: "admin@gmail.com", name: "Admin", password_digest: "$2a$10$sK7CyAluuAzfGyvDyvjcHOPL8TLnMbaLG0Ir6bRpr3MxO04ZFmAQW"},
  {email: "emily@gmail.com", name: "Emily Flanagan", password_digest: "$2a$10$.Wu5WOhjMKQFkJu6QZANo.G6ba2HkaXMdtN9ykkrUYCp35Qxg9swK"},
  {email: "emily@gmail.com", name: "Emily Flanagan", password_digest: "$2a$10$CnHcJrXL.P3ZO0WoPJU28.xB61hpeq.wfIMf/yFwMSrj0ODIxy2x2"},
  {email: "qzzzq1@gmail.com", name: "colin", password_digest: "$2a$10$feZneIhJnwLEa4gcPoxkfe0BpCG7rz3r0GCElyk2aTzBI/bCoS5bG"},
  {email: "qzzzq1@gmail.com", name: "colin2", password_digest: "$2a$10$3j783FRzweWSfAd29bStYem56ecdkTNVu4Nop9EJAB5.9WXK4EFt2"},
  {email: "qzzzq1@gmail.com", name: "colin2", password_digest: "$2a$10$/M2VbXrWE8XsGM8gEITqhePCW4AuFf.7eNlwUC9b02Uk1KgPe7VIS"},
  {email: "qzzzq1@gmail.com", name: "colin2", password_digest: "$2a$10$0uDk5EoS3W4Ec0FQdsAVbOzyEF9ZXVMf0ZXf7WTXBe1m4d/NE7KxC"},
  {email: "qzzzq1@gmail.com", name: "colin2", password_digest: "$2a$10$EdbkLbo1I9mtCmIoM84CE.J.zRKaYd8MGr5J6Pl8NnlBySC6fdM8u"},
  {email: "qzzzq1@gmail.com", name: "colin2", password_digest: "$2a$10$vClJeGD7RL1l1IIJc3aGU.4QteuHTd7DbYIKpxZ8VKMjATR369R4i"},
  {email: "qzzzq1@gmail.com", name: "colin2", password_digest: "$2a$10$SjByLU7URlDD.G2rPgKA6ehQXXVUXdA475YGel.suY2fnvW2YlH4C"},
  {email: "qzzzq1@gmail.com", name: "colin3", password_digest: "$2a$10$nyPL6WLOdRLmlvjyycQPfuto7xR8MhWui0pRHhe1QmP2bPthgcwFy"},
  {email: "qzzzq1@gmail.com", name: "colin3", password_digest: "$2a$10$Y5lcWfx0l2XQjoAANeDj2Onf0ofzNN6tGkX8TJYvgAMnjpu8irWHC"},
  {email: "b@gmail.com", name: "b", password_digest: "$2a$10$PeKdrqvrROq2fEhlksl3HuVTpLS/BXCGq0qku//85GtO/Sic16Zc6"},
  {email: "f@gmail.com", name: "f", password_digest: "$2a$10$HWPpmIvsZCBGMGtUIM29uuv.MnopgCv0mdMOKBm6A.QlF2uxKAQLS"},
  {email: "z@gmail.com", name: "z", password_digest: "$2a$10$MMF3mowBkEr3IvkV2XdRd.bYyo9axgNIzVRzhXJ0F0iRru2zH2K4q"},
  {email: "k@gmail.com", name: "k", password_digest: "$2a$10$RrQtpAEe/b.bqUDVGioDwuut6mvW1vjAymUjFrl5tLPmqyk1bFhY6"},
  {email: "k@gmail.com", name: "k", password_digest: "$2a$10$Dliy8uE2qfWJdst/7BHvH.LKT6hWzHYJDSUj0UVm1W2g38JbYC8MS"},
  {email: "t@gmail.com", name: "T", password_digest: "$2a$10$IcSXXC7GLaEhYFMhR7ZW7.6qj1NrlbCW3KIa5rFzqsbPU0l.Hw/u2"},
  {email: "emily@gmail.com", name: "Emily", password_digest: "$2a$10$l5Kz7x8HCyz06UDbIpxytOViEManK0hIahj3aAUe1fIfCAlA2RTvq"},
  {email: "a@gmail.com", name: "asdf", password_digest: "$2a$10$OguoeBhNBDzpgjay5gk5WeQRcNstjeONMwYjpxBntVqGAsf2FoLmi"},
  {email: "a@gmail.com", name: "easd", password_digest: "$2a$10$3HCR2RYdVHXq5VEK.2l2rOxUXSTAN7hlTrDnvU3L2QY97tK/3E9TK"},
  {email: "a@gmail.com", name: "a", password_digest: "$2a$10$7pg5vknZJILnVmjGWYXZWejAEymaXMX7WUUQUzAGH5FSeUOCS0Cue"},
  {email: "j@gmail.com", name: "j", password_digest: "$2a$10$rjE3tvtEJ8UKCW.FqxBWVO19.aKYU/umDz/RtdC0Tpa.MHch6Lyt2"},
  {email: "g@gmail.com", name: "g", password_digest: "$2a$10$kbzcwJubbWlC/RXwe1tuyOuodYxzL2lDr6IMyl724/X0eR1ut3/TO"},
  {email: "flanagan.emily.j@gmail.com", name: "e", password_digest: "$2a$10$jhogtnB4UUuPWiz6xE4PK.gelSvJCZ4mbJaYtuxmZlfy7SrXoo3/O"},
  {email: "v@gmail.com", name: "v", password_digest: "$2a$10$jopUM8CsrEKgjrpn7WOh.ucJ.PvZJKth/ysLFP8ZisHHpr8ptz7PO"},
  {email: "va@gmail.com", name: "va", password_digest: "$2a$10$Hr9XHpfZbBZsWkr3WYMtl.2oibw71i.jtI/Ni7FMvnyr.f1j4WcJe"},
  {email: "r@gmail.com", name: "ra", password_digest: "$2a$10$6ii7H3ICJ6TLW0iLNBJ3kehvEZTTqyUHEm1oi.WMCAESF/XxtJ4Jy"},
  {email: "mo@gmail.com", name: "mo", password_digest: "$2a$10$P7XJfgSbtsXgEbeGopJaSuU/A.N7Fs/ntEXAFpNUx/tuQOS9E81TW"},
  {email: "lo@gmail.com", name: "lo", password_digest: "$2a$10$qubF5VVTYlOym2Dubz1RP.ooMZWLGCqYLLwgGj5nd7Wf.TtMEXogG"},
  {email: "ruby@gmail.com", name: "ruby", password_digest: "$2a$10$stdMYIqbGpFkPmukjtZep.DSguTFtOG2dn6cZERpk/Mv4zCyuOEZe"},
  {email: "hi@gmail.com", name: "hi", password_digest: "$2a$10$584MhokGRe1R5Skd08.7eOasCpj15ECYldeYDjk4IiOuwH9cH4QL."},
  {email: "aa@gmail.com", name: "aa", password_digest: "$2a$10$HX7BEkTPgkir7n/YkoDPZeyySyxPemEYtp5HPsBqhs15W4IBkshXy"},
  {email: "bb@gmail.com", name: "bb", password_digest: "$2a$10$xP9nrt9yroEEUjT3aX3zcOwiVpku9WY7M51ZU4lwCvF5E83hvZd16"},
  {email: "cc@gmail.com", name: "cc", password_digest: "$2a$10$buvOu7OycwqnvAWvAXD45ucRz6odlb8S20zmXemlY1xyuZooI0Jwm"},
  {email: "dd@gmail.com", name: "dd", password_digest: "$2a$10$O1yYma85F6MIJnOeq5ICouEy6da6kSNBslaRQGrMXrNRAvmKeS97W"},
  {email: "jj@gmail.com", name: "jj", password_digest: "$2a$10$F8HaYcZe8npBKKlfJzYDLOOo4mUyaAOOOlTwA2UmTp8CRAnN7eFXK"},
  {email: "zz@gmail.com", name: "zz", password_digest: "$2a$10$ZMw1P.ztuY.LVF6ntH3DneKZ7O50F7I9Xk5voEy4ajNn5Kl9CpLFi"},
  {email: "tt@gmail.com", name: "tt", password_digest: "$2a$10$wV1nqhJMQRuTC./bEcX2Nu66jWOvzzjdfOzrJ0429Hkkm2CCY/q0G"},
  {email: "ss@gmail.com", name: "ss", password_digest: "$2a$10$krsk65y70VlN3NUbk4NQqu5W4QCAubvMrDI2fmyShVfO3h9hasqqO"},
  {email: "ee@gmail.com", name: "ee", password_digest: "$2a$10$EKLWgVhqZ4t8f9Iv7fV4h.joQM/uug3tSWuBb6A40am3zA8GD5rI."},
  {email: "ff@gmail.com", name: "ff", password_digest: "$2a$10$85HosKST2z70tOX/w1fi5elhmmc7U/ssObl2qBmrZ0Vq3WaNSlczq"},
  {email: "y@gmail.com", name: "y", password_digest: "$2a$10$aNPVjKD4z0XPPWbtPTRq5eQtB2qEmc4k5EwBfADSy8mFh12wHnquW"},
  {email: "calimeetme@gmail.com", name: "Ruby", password_digest: "$2a$10$tfO3X38Rn0yMKlunL88ll.X00WV4u8ZST7T46rT/1jeV7U.gx5SJO"},
  {email: "calimeetme@gmail.com", name: "Joy", password_digest: "$2a$10$ibTCTyfpG82W.IzasJNsf.BqhQIWvMAZBN9J2m3wiXk5qNCW9Q7zS"}
])
Userpoll.create!([
  {user_id: 4, poll_id: 1},
  {user_id: 5, poll_id: 2},
  {user_id: 17, poll_id: 6},
  {user_id: 18, poll_id: 7},
  {user_id: 18, poll_id: 8},
  {user_id: 18, poll_id: 9},
  {user_id: 18, poll_id: 10},
  {user_id: 18, poll_id: 11},
  {user_id: 18, poll_id: 12},
  {user_id: 18, poll_id: 13},
  {user_id: 18, poll_id: 14},
  {user_id: 19, poll_id: 15},
  {user_id: 20, poll_id: 16},
  {user_id: 20, poll_id: 17},
  {user_id: 20, poll_id: 18},
  {user_id: 20, poll_id: 19},
  {user_id: 20, poll_id: 20},
  {user_id: 21, poll_id: 21},
  {user_id: 22, poll_id: 22},
  {user_id: 22, poll_id: 23},
  {user_id: 22, poll_id: 24},
  {user_id: 22, poll_id: 25},
  {user_id: 22, poll_id: 26},
  {user_id: 22, poll_id: 27},
  {user_id: 22, poll_id: 28},
  {user_id: 22, poll_id: 29},
  {user_id: 22, poll_id: 30},
  {user_id: 22, poll_id: 31},
  {user_id: 22, poll_id: 32},
  {user_id: 22, poll_id: 33},
  {user_id: 22, poll_id: 34},
  {user_id: 22, poll_id: 35},
  {user_id: 22, poll_id: 36},
  {user_id: 22, poll_id: 37},
  {user_id: 22, poll_id: 38},
  {user_id: 22, poll_id: 39},
  {user_id: 23, poll_id: 40},
  {user_id: 24, poll_id: 41},
  {user_id: 24, poll_id: 42},
  {user_id: 25, poll_id: 43},
  {user_id: 26, poll_id: 44},
  {user_id: 26, poll_id: 45},
  {user_id: 26, poll_id: 46},
  {user_id: 27, poll_id: 47},
  {user_id: 27, poll_id: 48},
  {user_id: 27, poll_id: 49},
  {user_id: 27, poll_id: 50},
  {user_id: 27, poll_id: 51},
  {user_id: 1, poll_id: 52},
  {user_id: 1, poll_id: 53},
  {user_id: 1, poll_id: 54},
  {user_id: 1, poll_id: 55},
  {user_id: 29, poll_id: 56},
  {user_id: 33, poll_id: 57},
  {user_id: 1, poll_id: 58},
  {user_id: 1, poll_id: 59},
  {user_id: 1, poll_id: 60},
  {user_id: 1, poll_id: 61},
  {user_id: 1, poll_id: 62},
  {user_id: 1, poll_id: 63},
  {user_id: 1, poll_id: 64},
  {user_id: 1, poll_id: 65},
  {user_id: 1, poll_id: 66},
  {user_id: 1, poll_id: 67},
  {user_id: 1, poll_id: 68},
  {user_id: 1, poll_id: 69},
  {user_id: 1, poll_id: 70},
  {user_id: 1, poll_id: 71},
  {user_id: 1, poll_id: 72},
  {user_id: 1, poll_id: 73},
  {user_id: 1, poll_id: 74},
  {user_id: 1, poll_id: 75},
  {user_id: 1, poll_id: 76},
  {user_id: 1, poll_id: 77},
  {user_id: 1, poll_id: 78},
  {user_id: 1, poll_id: 79},
  {user_id: 1, poll_id: 80},
  {user_id: 1, poll_id: 81},
  {user_id: 1, poll_id: 82},
  {user_id: 1, poll_id: 83},
  {user_id: 1, poll_id: 84},
  {user_id: 1, poll_id: 85},
  {user_id: 1, poll_id: 86},
  {user_id: 48, poll_id: 87},
  {user_id: 1, poll_id: 88},
  {user_id: 1, poll_id: 89},
  {user_id: 1, poll_id: 90},
  {user_id: 1, poll_id: 91},
  {user_id: 49, poll_id: 92},
  {user_id: 49, poll_id: 93},
  {user_id: 49, poll_id: 94},
  {user_id: 49, poll_id: 95},
  {user_id: 30, poll_id: 96},
  {user_id: 30, poll_id: 97},
  {user_id: 30, poll_id: 98},
  {user_id: 30, poll_id: 99},
  {user_id: 30, poll_id: 100},
  {user_id: 1, poll_id: 101},
  {user_id: 50, poll_id: 102},
  {user_id: 50, poll_id: 103},
  {user_id: 50, poll_id: 104},
  {user_id: 50, poll_id: 105},
  {user_id: 50, poll_id: 106},
  {user_id: 50, poll_id: 107},
  {user_id: 50, poll_id: 108},
  {user_id: 50, poll_id: 109},
  {user_id: 1, poll_id: 110},
  {user_id: 1, poll_id: 111},
  {user_id: 1, poll_id: 112},
  {user_id: 1, poll_id: 113},
  {user_id: 1, poll_id: 114}
])
